services:
  neo4j:
    container_name: neo4j_server
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo-admin
      # - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}  # todo: not working properly.
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./../data/neo4j_db/logs:/logs
      - ./../data/neo4j_db/config:/config
      - ./../data/neo4j_db/data:/data
      - ./../data/neo4j_db/plugins:/plugins
      - ./../data/neo4j_db/import:/var/lib/neo4j/import
  