[project]
name = "graphrag-neo4j-vmd-namd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marker-pdf>=1.6.2",
    "streamlit>=1.44.1",
]
