################################
# NOT ALL KEYS ARE REQUIRED.
# See README for more details.
################################

# LangSmith
# LANGCHAIN_TRACING_V2 = "true"  # deprecated
# LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"  # deprecated
# LANGCHAIN_API_KEY = "YOUR_API_KEY"  # deprecated

LANGSMITH_TRACING = "true"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
LANGSMITH_API_KEY = "YOUR_API_KEY"
# LANGSMITH_PROJECT="PROJECT_NAME"  # Is it needed?

# ------------------------------
# OpenAI API
OPENAI_API_KEY = "YOUR_API_KEY"

# ------------------------------
# Google Gemini API
GOOGLE_API_KEY = "OUR_API_KEY"

# ------------------------------
# MongoDB Atlas
MONGODB_URI = "CONNECTION_STRING"

# ------------------------------
# Neo4j
NEO4J_USERNAME = "neo4j"  # default username

## Neo4j - Local (Docker/Native)
NEO4J_URI = "bolt://localhost:7687"
NEO4J_PASSWORD = "${file:.env-docker-neo4j}"

## Neo4j - Cloud
# NEO4J_URI = "neo4j+s://<Instance_ID>.databases.neo4j.io"
# NEO4J_PASSWORD = "<Instance_Password>"

# ------------------------------
