# This file will be used with dotenv package
# See https://pypi.org/project/python-dotenv/ for more details

### NOT ALL KEYS ARE REQUIRED ###

# LangSmith API
# https://smith.langchain.com
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "YOUR_API_KEY"  # from https://smith.langchain.com

# OpenAI API
OPENAI_API_KEY = "YOUR_API_KEY"  # from https://platform.openai.com/api-keys

# Google Gemini API
GEMINI_API_KEY = "OUR_API_KEY"  # from https://ai.dev

# MongoDB Atlas
# For additional help, see https://www.mongodb.com/docs/atlas/troubleshoot-connection/#special-characters-in-connection-string-password
MONGODB_URI = "CONNECTION_STRING"  # from https://cloud.mongodb.com -> Clusters -> Connect -> Driver -> Python

# Neo4j
NEO4J_URI = "bolt://localhost:7687"  # for local via docker or native
NEO4J_USERNAME = "neo4j"  # default username
NEO4J_PASSWORD = "${file:.env-neo4j-auth | sed 's/^neo4j\///'}"  # import password from file and remove "neo4j/" prefix if present
